language: go
go:
  - 1.3
  - tip
before_install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:zfs-native/stable
  - sudo apt-get update
install:
  - sudo apt-get install ubuntu-zfs libzfs-dev
before_script:
  - fallocate -l 1G /tmp/zstore1.img
  - fallocate -l 1G /tmp/zstore2.img
  - fallocate -l 1G /tmp/zstore3.img
  - fallocate -l 1G /tmp/zstore4.img
  - sudo zpool create zstore /tmp/zstore1.img /tmp/zstore2.img /tmp/zstore3.img /tmp/zstore4.img
  - sudo zpool status zstore
script:
  - go get -d ./...
  - go test -v ./...
  - go install ./...
  - sudo zstored
